hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

discord_login:
    path: /login/check
    defaults: { _remember_me: on }

logout:
    path: /logout

# higher priority for vanityinvites
robyul_vanityinvite:
    resource: "@RobyulWebBundle/VanityInviteController/"
    type:     annotation
    prefix:   /
    host:    '%vanityinvite_domain%'

robyul_web:
    resource: "@RobyulWebBundle/Controller/"
    type:     annotation
    prefix:   /
    host:    '%default_domain%'
