# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        hwi:
            id: discord_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            provider: hwi
            logout_on_user_change: true
            anonymous: ~
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    discord:       "/login/check"
                use_forward:       false
                login_path:        /connect/discord
                default_target_path: /d/profile
                failure_path:      /

                oauth_user_provider:
                    service: discord_user_provider
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 # 1 month
                path:     /
                always_remember_me: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/d/, roles: ROLE_DISCORD_USER }