parameters:
    discord_user_provider.class: RobyulWebBundle\Security\Core\User\DiscordUserProvider

services:
#    robyul_web.example:
#        class: RobyulWebBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    discord_user_provider:
        class: "%discord_user_provider.class%"
        arguments: ['@snc_redis.default']