parameters:
    robyul_api_service.class: RobyulWebBundle\Service\RobyulApi
    discord_user_provider.class: RobyulWebBundle\Security\Core\User\DiscordUserProvider

services:
    robyul_api_service:
        class: "%robyul_api_service.class%"
        arguments: ['@service_container', '@logger']
    discord_user_provider:
        class: "%discord_user_provider.class%"
        arguments: ['@robyul_api_service']